name: Build Windows App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project with Maven
        run: mvn clean package

      - name: Prepare JavaFX
        run: |
          curl -L -o javafx.zip https://download2.gluonhq.com/openjfx/21.0.1/openjfx-21.0.1_windows-x64_bin-sdk.zip
          tar -xf javafx.zip

      - name: Create Windows EXE with jpackage
        run: |
          jpackage ^
            --type exe ^
            --name TechPasport ^
            --input target ^
            --main-jar TechPasport-1.0-SNAPSHOT.jar ^
            --main-class zakir.alekperov.bootstrap.ApplicationLauncher ^
            --java-options "--module-path javafx-sdk-21.0.1/lib --add-modules javafx.controls,javafx.fxml" ^
            --dest dist

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: TechPasport-windows
          path: dist
